pipeline:
  run-koa-react-starter-tests:
    image: node:10.16.0
    commands:
      - ./bin/run.sh
    when:
      status: [ failure, success ]
      event: [ pull_request ]

branches: [ master, "*:master" ]
